### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by langsharpe** [everydayhero/tech-talks#31]
- What is time?
- Interesting representations of points in time
- What is a timezone? (offsets, Daylight savings, TZInfo)
- Time, Date and DateTime types in Rails
- Date calculations are weird

**Comment by dn-readytech** [comment]
+1

**Comment by evilmarty** [comment]
:+1: There was a talk about timezones at JSConf. Once the video is online I will share the link.

**Comment by leonfu103** [comment]
:+1:

**Comment by joelr** [comment]
This is marked as a the 26th, conflict with Craig's?

**Comment by joelr** [comment]
unless the secret talk Craig is presenting is about timezones.

**Comment by langsharpe** [comment]
Mr Tim E Zones is the secret guest.

I'm not ready, so it's down to Craig.
