### ISSUE TITLE
Why do we need to develop a UBL

### ISSUE THREAD

**Issue by coop** [everydayhero/tech-talks#33]
In the past I've watched eyes glaze over when @JonathonMA has mentioned "UBL" or "Ubiquitous Language" and I believe it's because we've never discussed what it is, why it's important and how it leads to deeper insights into the codebase.

I see this presentation taking roughly 10 minutes so I'd be happy to share a slot with someone else.

**Comment by langsharpe** [comment]
:+1:

**Comment by joelr** [comment]
:+1:
