### ISSUE TITLE
What the Flux is React?

### ISSUE THREAD

**Issue by davidherse** [everydayhero/tech-talks#36]
What the Flux is React?

**Comment by dn-readytech** [comment]
+1

**Comment by janahanEDH** [comment]
:+1:

**Comment by nippysaurus** [comment]
:+1:

**Comment by langsharpe** [comment]
:+1:

**Comment by joelr** [comment]
:+1:

**Comment by evilmarty** [comment]
:+1:

**Comment by orodio** [comment]
:+1:

**Comment by coop** [comment]
:+1: and I'd also like to hear why it's being chosen over Ember (etc).

**Comment by orodio** [comment]
I will do the react side of things if @davidherse does the flux side of things...

**Comment by orodio** [comment]
@davidherse and I will do this june 26th

**Comment by dn-readytech** [comment]
June 26th is unavailable—lock in June 3rd.

**Comment by JonathonMA** [comment]
> june 26th

suck it @langsharpe

**Comment by langsharpe** [comment]
I'm happy to drop out this week (not nearly ready). Also, this email from Craig. (You guys do read email, right?)

---

Hi Everyone

For those of us who will be in the Brisbane office next Thursday, please keep your diaries free for an hour to attend "a Brown Bag session of a different kind".

We will be inviting special guest speakers from outside the EDH/Blackbaud world to join us….

_Ooooooh!!!_

More details to follow next week.
Have a lovely weekend.

Craig Shackleton

---

**Comment by davidherse** [comment]
We'll postpone.

**Comment by coop** [comment]
This was a good talk.

**Comment by langsharpe** [comment]
@orodio Can you add the slides?
