### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by nippysaurus** [everydayhero/tech-talks#39]

**Comment by orodio** [comment]
buddy... https://github.com/everydayhero/tech-talks/issues/1

**Comment by nippysaurus** [comment]
I did a search, but didn't realise there were multiple pages >.<

Thanks.

**Comment by JonathonMA** [comment]
Maybe if we stored our tech talks in some kind of searchable JSON store. Perhaps...solr?

**Comment by joelr** [comment]
@JonathonMA let's go with Sphinx.. I've heard great things...

:trollface:
