### ISSUE TITLE
Acceptance Test Driven Development

### ISSUE THREAD

**Issue by colinbankier** [everydayhero/tech-talks#4]
How it enables continuous delivery, reduces waste, and helps you deliver the product the customer actually wanted. How to actually do it.

**Comment by colinbankier** [comment]
:+1:

**Comment by janahanEDH** [comment]
:+1:

**Comment by langsharpe** [comment]
:+1:

**Comment by leonfu103** [comment]
:+1:

**Comment by langsharpe** [comment]
@JonathonMA Link to slides?

**Comment by JonathonMA** [comment]
i'll try

poke me if I haven't done anything in a week
