### ISSUE TITLE
Cause Mappings

### ISSUE THREAD

**Issue by nippysaurus** [everydayhero/tech-talks#40]

**Comment by coop** [comment]
What do you want to know about this?

**Comment by joelr** [comment]
yes, this doesn't feel like a brownbag

**Comment by nippysaurus** [comment]
> What do you want to know about this?

What are cause mappings, how is the data imported and where from, how is it mapped to charities, what purpose does it serve, etc.

I feel like it is a simple concept which is shrouded in mystery because the code is a little complex, hence the request for clarification.
