### ISSUE TITLE
Functional Programming - building concurrent systems

### ISSUE THREAD

**Issue by colinbankier** [everydayhero/tech-talks#7]
As we move to more concurrent and distributed systems, our current programming paradigms are insufficient.

"Mutable stateful objects are the new spaghetti code:
- hard to understand, test, reason about
- Concurrency disaster" 

(Rick Hickey)

**Comment by orodio** [comment]
:+1:

**Comment by coop** [comment]
Can we close this in favour of the Tuesday sessions with @markryall?
